[package]
name = "atoi"
version = "0.1.0"
authors = ["Brad Gibson <b2b@humanenginuity.com>"]

[dependencies]

[profile.release]
codegen-units = 1
debug = true
debug-assertions = false
lto = true
opt-level = 3
panic = "unwind"
rpath = false

